server:
  port: 22222
  servlet:
    context-path: /api
spring:
  application:
    name: xc-govern-gateway
eureka:
  client:
    service-url:
      defaultZone: http://192.168.56.133:11111/eureka/ #,http://localhost:50102/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
ribbon:
  MaxAutoRetries: 2 #最大重试次数，当Eureka中可以找到服务，但是服务连不上时将会重试，如果eureka中找不到服务则直接走断路器
  MaxAutoRetriesNextServer: 3 #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 5000  #请求连接的超时时间
  ReadTimeout: 6000 #请求处理的超时时间
zuul:
  routes:
    manage-course:
      path: /course/** # 路由配置
      serviceId: xc-service-manage-course # 服务id
      # 配置了这两个之后，请求localhost:22222/api/course之后，就会转发到localhost:33333/course
      # url: http://localhost:33333 #也可指定url
      strip-prefix: false # 代理转发时是否去掉前缀，即把/course去掉，这里不去掉，因为我们的课程服务就是以/course打头的
      sensitiveHeaders: # 不屏蔽cookie